## <center>**KECERDASAN ARTIFISIAL UNTUK GEOFISIKA**</center>
### <center>**Pembuatan Recipe — Analisis Data Geolistrik Resistivitas**</center>

#### **NAMA**: **MUHAMMAD FAIZ AUDHADI HERAWAN**  
#### **NIM**: **H061231024**  
#### **KELAS**: **A**

<hr>

## Judul
**Identifikasi Variasi Resistivitas dan Perkiraan Lapisan Bawah Permukaan Menggunakan Metode Geolistrik Resistivitas Konfigurasi Schlumberger (VES).**

### Identitas recipe

| Komponen | Keterangan |
|---|---|
| Recipe ID | R-GEO-002 |
| Prompt ID | P-GEO-002 |
| Data utama | Jarak elektroda dan hasil pengukuran beda potensial serta arus, atau nilai resistansi |
| Metode analisis | Geolistrik resistivitas, konfigurasi Schlumberger |
| Luaran | Resistivitas semu, kurva sounding, tabel hasil, dan interpretasi awal |

## 1. Problem — Permasalahan
Metode geolistrik resistivitas digunakan untuk mempelajari variasi sifat kelistrikan material bawah permukaan. Pengukuran dilakukan dengan menginjeksikan arus melalui elektroda arus dan mengukur beda potensial melalui elektroda potensial. Nilai resistivitas semu dihitung dari resistansi terukur dan faktor geometri elektroda.

Tantangan analisis meliputi pemeriksaan data lapangan, penerapan faktor geometri yang benar, visualisasi kurva resistivitas semu, dan interpretasi yang tidak melampaui dukungan data. Recipe ini menggunakan konfigurasi Schlumberger untuk sounding listrik vertikal (Vertical Electrical Sounding/VES). Hasil kurva resistivitas semu merupakan tahap awal; penentuan resistivitas dan ketebalan lapisan sebenarnya umumnya memerlukan pemodelan inversi dan informasi geologi pendukung.

## 2. Minimal Theory — Dasar Teori

### Resistansi terukur
Jika beda potensial \\(\\Delta V\\) dan arus listrik \\(I\\) tersedia, resistansi dihitung dengan:

\\[
R = \\frac{\\Delta V}{I}
\\]

Jika alat sudah memberikan nilai resistansi, nilai tersebut dapat langsung digunakan setelah satuan dan kualitas pengukuran diperiksa.

### Resistivitas semu
Resistivitas semu dihitung dengan:

\\[
\\rho_a = K R
\\]

Untuk konfigurasi Schlumberger, dengan \(AB/2=a\) dan \(MN/2=b\), faktor geometri adalah:

\\[
K = \\frac{\\pi(a^2-b^2)}{2b}
\\]

Keterangan:
- \\(\\rho_a\\): resistivitas semu (\\(\\Omega\\cdot m\\)).
- \\(K\\): faktor geometri (m).
- \\(R\\): resistansi (\\(\\Omega\\)).
- \\(AB/2\\): setengah jarak elektroda arus (m).
- \\(MN/2\\): setengah jarak elektroda potensial (m).

Rumus tersebut berlaku untuk susunan Schlumberger simetris dengan \(AB/2 > MN/2 > 0\). Pastikan definisi jarak pada catatan lapangan sesuai dengan rumus ini.

### Interpretasi awal
- Nilai resistivitas rendah dapat berkaitan dengan material lempungan, tanah jenuh air, atau fluida yang lebih konduktif.
- Nilai resistivitas tinggi dapat berkaitan dengan batuan kompak, material kering, atau batuan dengan porositas rendah.
- Rentang resistivitas berbagai litologi saling tumpang tindih. Karena itu, resistivitas tidak boleh digunakan sendiri untuk memastikan jenis batuan, keberadaan air tanah, atau kondisi geologi tertentu.

## 3. Input — Data yang Dibutuhkan

Data utama per pengukuran:
- Kode titik sounding.
- \(AB/2\) (m).
- \(MN/2\) (m).
- Resistansi \(R\) (ohm), atau beda potensial \\(\\Delta V\\) (V/mV) dan arus \(I\) (A/mA).

Metadata pendukung:
- Koordinat titik pengukuran dan elevasi.
- Konfigurasi elektroda yang digunakan.
- Satuan asli data dan catatan kondisi lapangan.
- Informasi geologi, singkapan, sumur, atau data pendukung lain jika tersedia.

Periksa nilai kosong, satuan, duplikasi, dan hubungan jarak elektroda sebelum menghitung resistivitas semu.

## 4. Prompt — Instruksi AI Siap Digunakan

### P-GEO-002 — Recipe Analisis Geolistrik Resistivitas

**Peran AI**  
Bertindaklah sebagai asisten analisis data geofisika yang memahami metode geolistrik resistivitas, konfigurasi Schlumberger, pemrosesan data, Python, serta interpretasi geologi bawah permukaan.

**Tujuan**  
Bantu saya memeriksa data sounding geolistrik, menghitung faktor geometri dan resistivitas semu, membuat kurva sounding, mendeteksi data yang perlu diperiksa, dan menyusun interpretasi awal secara hati-hati.

**Input**  
Saya akan menyediakan tabel berisi kode titik, \(AB/2\), \(MN/2\), dan resistansi \(R\), atau beda potensial dan arus. Periksa format, satuan, konfigurasi, dan kualitas data terlebih dahulu. Jangan mengarang data lapangan atau menganggap contoh sintetis sebagai hasil pengukuran nyata.

**Tahapan analisis**
1. Periksa kelengkapan, satuan, nilai negatif/nol, duplikasi, dan konsistensi jarak elektroda.
2. Hitung faktor geometri Schlumberger.
3. Hitung resistivitas semu untuk setiap pengukuran.
4. Buat tabel hasil dan plot \\(\\rho_a\\) terhadap \(AB/2\) pada skala logaritmik.
5. Tandai nilai anomali atau titik yang perlu diperiksa, tanpa menghapus data otomatis.
6. Jelaskan bentuk kurva secara deskriptif dan nyatakan bahwa kurva resistivitas semu bukan model lapisan final.
7. Jika data dan perangkat inversi tersedia, jelaskan kebutuhan inversi untuk memperkirakan resistivitas dan ketebalan lapisan.
8. Sajikan interpretasi dengan menyebutkan ketidakpastian dan kebutuhan data geologi pendukung.

**Batasan**  
Jangan menyimpulkan litologi, kedalaman akuifer, atau ketebalan lapisan secara pasti hanya dari satu nilai resistivitas semu. Bedakan data terukur, hasil perhitungan, dan interpretasi.

## Rancangan Workflow Python

1. **Input data** — masukkan data lapangan \(AB/2\), \(MN/2\), dan \(R\), atau baca dari CSV.
2. **QA/QC** — periksa satuan, nilai kosong, nilai nonpositif, dan geometri elektroda.
3. **Perhitungan** — hitung faktor geometri Schlumberger dan resistivitas semu.
4. **Visualisasi** — tampilkan kurva \\(\\rho_a\\) terhadap \(AB/2\) pada sumbu logaritmik.
5. **Ekspor dan interpretasi** — simpan tabel ke CSV dan tuliskan interpretasi awal dengan batasan yang jelas.

**Catatan:** Data di sel kode berikut adalah contoh sintetis untuk menunjukkan cara kerja kode. Ganti dengan data lapangan sebelum melakukan interpretasi penelitian.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# ==========================================================
# A. INPUT DATA
# ==========================================================
# GANTI data contoh ini dengan data pengukuran lapangan.
# Semua jarak menggunakan meter dan resistansi menggunakan ohm.
data = pd.DataFrame({
    "titik": ["VES-01"] * 8,
    "AB2_m": [1.0, 1.5, 2.0, 3.0, 4.0, 6.0, 8.0, 10.0],
    "MN2_m": [0.2, 0.2, 0.2, 0.5, 0.5, 0.5, 1.0, 1.0],
    "R_ohm": [18.0, 12.5, 9.2, 6.4, 4.8, 3.1, 2.6, 2.1]
})

data

    titik  AB2_m  MN2_m  R_ohm
0  VES-01    1.0    0.2   18.0
1  VES-01    1.5    0.2   12.5
2  VES-01    2.0    0.2    9.2
3  VES-01    3.0    0.5    6.4
4  VES-01    4.0    0.5    4.8
5  VES-01    6.0    0.5    3.1
6  VES-01    8.0    1.0    2.6
7  VES-01   10.0    1.0    2.1

In [ ]:
# ==========================================================
# B. QA/QC DATA
# ==========================================================
required = ["titik", "AB2_m", "MN2_m", "R_ohm"]
missing_cols = [col for col in required if col not in data.columns]
if missing_cols:
    raise ValueError(f"Kolom wajib tidak tersedia: {missing_cols}")

for col in ["AB2_m", "MN2_m", "R_ohm"]:
    data[col] = pd.to_numeric(data[col], errors="coerce")

if data[["AB2_m", "MN2_m", "R_ohm"]].isna().any().any():
    raise ValueError("Ada nilai kosong atau nonnumerik pada kolom jarak/resistansi.")

if (data["AB2_m"] <= 0).any() or (data["MN2_m"] <= 0).any():
    raise ValueError("AB/2 dan MN/2 harus lebih besar dari nol.")

if (data["AB2_m"] <= data["MN2_m"]).any():
    raise ValueError("Untuk rumus ini, AB/2 harus lebih besar daripada MN/2.")

if (data["R_ohm"] <= 0).any():
    raise ValueError("Resistansi harus positif. Periksa data dan satuannya.")

print(f"Jumlah data: {len(data)}")
print("Pemeriksaan dasar selesai. Tinjau juga catatan lapangan dan satuan instrumen.")

In [2]:
# ==========================================================
# C. HITUNG FAKTOR GEOMETRI DAN RESISTIVITAS SEMU
# ==========================================================
a = data["AB2_m"].to_numpy(dtype=float)
b = data["MN2_m"].to_numpy(dtype=float)
R = data["R_ohm"].to_numpy(dtype=float)

K = np.pi * (a**2 - b**2) / (2 * b)
data["K_m"] = K
data["rho_a_ohm_m"] = K * R

display(data)

    titik  AB2_m  MN2_m  R_ohm         K_m  rho_a_ohm_m
0  VES-01    1.0    0.2   18.0    7.539822   135.716803
1  VES-01    1.5    0.2   12.5   17.357299   216.966243
2  VES-01    2.0    0.2    9.2   31.101767   286.136259
3  VES-01    3.0    0.5    6.4   27.488936   175.929189
4  VES-01    4.0    0.5    4.8   49.480084   237.504405
5  VES-01    6.0    0.5    3.1  112.311937   348.167006
6  VES-01    8.0    1.0    2.6   98.960169   257.296438
7  VES-01   10.0    1.0    2.1  155.508836   326.568556

In [ ]:
# ==========================================================
# E. RINGKASAN DAN EKSPOR HASIL
# ==========================================================
print("Rentang AB/2 (m):", data["AB2_m"].min(), "–", data["AB2_m"].max())
print("Rentang resistivitas semu (ohm m):",
      round(data["rho_a_ohm_m"].min(), 3), "–",
      round(data["rho_a_ohm_m"].max(), 3))

# Simpan hasil pada folder kerja notebook.
output_file = Path("hasil_resistivitas_semu.csv")
data.to_csv(output_file, index=False)
print("Tabel hasil disimpan ke:", output_file.resolve())

print(
    "\nInterpretasi awal: amati perubahan tren kurva resistivitas semu "
    "terhadap AB/2. Jangan mengubah tren ini langsung menjadi kedalaman "
    "atau litologi tanpa inversi dan informasi geologi pendukung."
)